<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://service.zubentsov.ru" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://service.zubentsov.ru" xmlns:intf="http://service.zubentsov.ru" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://service.zubentsov.ru" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="getTime">
    <complexType/>
   </element>
   <element name="getTimeResponse">
    <complexType>
     <sequence>
      <element name="getTimeReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="getTimeRequest">

      <wsdl:part element="impl:getTime" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="getTimeResponse">

      <wsdl:part element="impl:getTimeResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="MyService">

      <wsdl:operation name="getTime">

         <wsdl:input message="impl:getTimeRequest" name="getTimeRequest">

       </wsdl:input>

         <wsdl:output message="impl:getTimeResponse" name="getTimeResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="MyServiceSoapBinding" type="impl:MyService">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="getTime">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getTimeRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="getTimeResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="MyServiceService">

      <wsdl:port binding="impl:MyServiceSoapBinding" name="MyService">

         <wsdlsoap:address location="http://localhost:8080/web/services/MyService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
